import type { Metadata } from 'next'
import './globals.css'
import Navbar from './components/NavBar'
import { NextAuthProvider } from '@/provider/AuthProvider'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={''}>
        <Navbar />
        <NextAuthProvider>
        {children}
        </NextAuthProvider>
        </body>
    </html>
  )
}
