
import type { Metadata } from 'next'
import './globals.css'
import { SessionProvider } from "next-auth/react"
import { NextAuthProvider } from '@/provider/AuthProvider';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type Props = {
  children: React.ReactNode;
  session: any;
};


export default function RootLayout({
  children, session,
}: 
  Props
) {
  return (
    <html lang="en">
      <body className={''}>
      <NextAuthProvider>{children}
      </NextAuthProvider></body>
    </html>
  )
}
